export {
  planService,
  resolveService,
  installedServices,
  legacyServices,
  legacyServiceHomeOf,
  serviceHomeOf,
  checkServiceName,
  systemdUnit,
  launchdLabel,
  SERVICE_NAME_RE,
  installService,
  uninstallService,
  serviceStatus,
  restartService,
  defaultEntry,
  shellQuote,
  type ServicePlan,
  type PlanOptions,
  type ServiceDeps,
  type CommandResult,
  type ServiceResult,
  type InstalledService,
} from './service.ts';
